<?php

return [
    'mailbox_provider' => 'ovh_mx_plan',

    'outbound_providers' => [
        'ovh_mx_plan' => [
            'label' => 'OVH MX Plan',
            'supports_imap' => true,
            'supports_sync' => true,
            'uses_mailbox_credentials' => true,
            'default_smtp_host' => 'smtp.mail.ovh.net',
            'default_smtp_port' => 465,
            'default_smtp_secure' => true,
        ],
        'smtp2go' => [
            'label' => 'SMTP2GO',
            'supports_imap' => false,
            'supports_sync' => false,
            'uses_mailbox_credentials' => false,
            'default_smtp_host' => env('SMTP2GO_SMTP_HOST', 'mail.smtp2go.com'),
            'default_smtp_port' => (int) env('SMTP2GO_SMTP_PORT', 587),
            'default_smtp_secure' => filter_var(env('SMTP2GO_SMTP_SECURE', false), FILTER_VALIDATE_BOOL),
        ],
    ],

    // All outbound sends share the same queue in V1, whether single or bulk.
    'queues' => [
        'outbound' => env('MAIL_OUTBOUND_QUEUE', 'mail-outbound'),
        'sync' => env('MAIL_SYNC_QUEUE', 'mail-sync'),
    ],

    'gateway' => [
        'driver' => env('MAIL_GATEWAY_DRIVER', 'stub'),
    ],

    'defaults' => [
        'general' => [
            'daily_limit_default' => 100,
            'hourly_limit_default' => 12,
            'min_delay_seconds' => 60,
            'jitter_min_seconds' => 5,
            'jitter_max_seconds' => 20,
            'slow_mode_enabled' => false,
            'stop_on_consecutive_failures' => 5,
            'stop_on_hard_bounce_threshold' => 3,
            'open_points' => 1,
            'click_points' => 2,
            'reply_points' => 8,
            'auto_reply_points' => 0,
            'soft_bounce_points' => -5,
            'hard_bounce_points' => -15,
            'unsubscribe_points' => -20,
            'inactivity_decay_days' => 30,
        ],
        'mail' => [
            'mailbox_provider' => 'ovh_mx_plan',
            'active_provider' => 'ovh_mx_plan',
            'sender_email' => '',
            'sender_name' => '',
            'global_signature_html' => null,
            'global_signature_text' => null,
            'mailbox_username' => '',
            'mailbox_password_configured' => false,
            'imap_host' => '',
            'imap_port' => 993,
            'imap_secure' => true,
            'sync_enabled' => true,
            'send_enabled' => true,
            'send_window_start' => '09:00',
            'send_window_end' => '18:00',
            'health_status' => 'unknown',
            'health_message' => null,
            'last_sync_at' => null,
            'providers' => [
                'ovh_mx_plan' => [
                    'provider' => 'ovh_mx_plan',
                    'label' => 'OVH MX Plan',
                    'smtp_host' => 'smtp.mail.ovh.net',
                    'smtp_port' => 465,
                    'smtp_secure' => true,
                    'smtp_username' => '',
                    'smtp_password_configured' => false,
                    'send_enabled' => true,
                    'supports_imap' => true,
                    'supports_sync' => true,
                    'configured' => false,
                    'activatable' => false,
                    'ready' => false,
                    'health_status' => 'unknown',
                    'health_message' => null,
                    'uses_mailbox_credentials' => true,
                ],
                'smtp2go' => [
                    'provider' => 'smtp2go',
                    'label' => 'SMTP2GO',
                    'smtp_host' => env('SMTP2GO_SMTP_HOST', 'mail.smtp2go.com'),
                    'smtp_port' => (int) env('SMTP2GO_SMTP_PORT', 587),
                    'smtp_secure' => filter_var(env('SMTP2GO_SMTP_SECURE', false), FILTER_VALIDATE_BOOL),
                    'smtp_username' => '',
                    'smtp_password_configured' => false,
                    'send_enabled' => true,
                    'supports_imap' => false,
                    'supports_sync' => false,
                    'configured' => false,
                    'activatable' => false,
                    'ready' => false,
                    'health_status' => 'unknown',
                    'health_message' => null,
                    'uses_mailbox_credentials' => false,
                ],
            ],
        ],
        'deliverability' => [
            'tracking_opens_enabled' => true,
            'tracking_clicks_enabled' => true,
            'max_links_warning_threshold' => 8,
            'max_remote_images_warning_threshold' => 3,
            'html_size_warning_kb' => 100,
            'attachment_size_warning_mb' => 10,
            'public_base_url' => env('MAIL_PUBLIC_BASE_URL'),
            'tracking_base_url' => env('MAIL_TRACKING_BASE_URL'),
        ],
    ],
];
